### ISSUE TITLE
Bump in Harmonic: gz-msgs and gz-transport

### ISSUE THREAD

**Issue by iche033** [gazebo-tooling/release-tools#878]
Libraries being bumped:

* gz-msgs10
    - [x] Source code of all downstream libraries ([example](https://github.com/gazebosim/gz-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/gazebo-release/gz-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/gazebo-tooling/release-tools/pull/437))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/gazebosim/docs/pull/175))

* gz-transport13
    - [x] Source code of all downstream libraries ([example](https://github.com/gazebosim/gz-transport/pull/149))
    - [x] Release repositories of all downstream libraries ([example](https://github.com/gazebo-release/gz-fuel-tools7-release/pull/1))
    - [x] Use `main` branch on `gazebodistro` ([example](https://github.com/gazebo-tooling/gazebodistro/pull/42))
    - [x] Build nightlies from the `main` branch ([example](https://github.com/gazebo-tooling/release-tools/pull/437))
    - [x] homebrew-simulation: create formula and update dependencies ([example](https://github.com/osrf/homebrew-simulation/pull/14230))
    - [x] docs (the collection’s page) ([example](https://github.com/gazebosim/docs/pull/175))

**Comment by j-rivero** [comment]
For the users failing into this error. Please first read [the recommendation of using a different Gazebo stable distribution](https://community.gazebosim.org/t/problem-to-build-gazebo-at-ubuntu-22-04-missing-dependency-gz-msgs9/1813/7?u=jrivero).

If you **really really** need to install Harmonic, as a temporary workaround until the source build works again when this issue is closed, nightly packages might be used (warning: nightly packages are also consider unstable and might now work as expected):

1. Install [gzdev](https://github.com/gazebo-tooling/gzdev#installation)
2. Enable the nightly repository from packages.osrfoundation.org
```sh
sudo python3 gzdev.py repository enable osrf nightly
```
3. Install the main -dev file for gz-launch (should bring most of the needed dependencies)
```sh
sudo apt-get install libgz-launch6-dev
```
